-- ClearFeed schema (PostgreSQL). Run once against the clearfeed database:
--     psql -U clearfeed -d clearfeed -f schema_postgres.sql
-- Fresh-database DDL. Existing SQL Server data is loaded separately by
-- scripts/migrate_sqlserver_to_postgres.py (which inserts explicit IDs, so the
-- IDENTITY columns are GENERATED BY DEFAULT).
--
-- Timestamp convention: naive US-Central datetimes, matching the prior T-SQL.
-- (now() AT TIME ZONE 'America/Chicago') yields a naive local timestamp — the
-- exact behavioral equivalent of the old
-- CONVERT(datetime2, SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time').
--
-- Identifiers are intentionally UNQUOTED everywhere in the app, so Postgres
-- folds them to lowercase (contentrecords, recordterms, ...). Do not quote
-- identifiers here or in queries — uniform lowercasing keeps profile SQL working.

CREATE TABLE IF NOT EXISTS ContentRecords (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type          VARCHAR(50)  NOT NULL,        -- gmail | file | manual
    source_ref           VARCHAR(500) NOT NULL,        -- Gmail message_id or file path
    received_at          TIMESTAMP    NULL,            -- original receive / file-modified time
    sender               VARCHAR(500) NULL,            -- From address; NULL for file sources
    subject              VARCHAR(1000) NULL,           -- email subject or filename
    body_text            TEXT         NULL,            -- stripped plain text (summarize/classify input)
    linked_article_url   VARCHAR(2000) NULL,           -- primary URL extracted from body
    image_local_paths    TEXT         NULL,            -- JSON array of stored image paths
    image_descriptions   TEXT         NULL,            -- JSON array of vision output (v2; NULL in v1)
    summary              TEXT         NULL,            -- LLM summary (set at ingest)
    executive_summary    TEXT         NULL,            -- summarize-step high-level summary
    summary_confidence   SMALLINT     NULL,            -- summarize-step certainty 1-5
    summary_rationale    VARCHAR(1000) NULL,           -- summarize-step explanation
    classification_confidence SMALLINT NULL,           -- classify-step certainty 1-5
    classification_rationale  VARCHAR(1000) NULL,      -- classify-step explanation
    classify_model       VARCHAR(50)  NULL,            -- full model ID used for the final classify call
    classify_tokens      INT          NULL,            -- total input+output tokens across classify calls
    escalated            BOOLEAN      NULL,            -- True if Sonnet re-call was triggered
    enrichment_status    VARCHAR(20)  NOT NULL DEFAULT 'pending',  -- pending | complete | failed
    enrich_attempt_count INT          NOT NULL DEFAULT 0,
    processed_at         TIMESTAMP    NULL,            -- when LLM fields were last computed (drives reprocess)
    ingested_at          TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'America/Chicago'),
    CONSTRAINT uq_content_source UNIQUE (source_type, source_ref)
);

CREATE INDEX IF NOT EXISTS ix_content_received ON ContentRecords (received_at DESC);
CREATE INDEX IF NOT EXISTS ix_content_enrichment ON ContentRecords (enrichment_status)
    WHERE enrichment_status IN ('pending', 'failed');

-- RecordTerms: generic queryable attributes on a record.
-- kind='label' terms are pushed to the Gmail thread; kind='tag' are LLM topics.
CREATE TABLE IF NOT EXISTS RecordTerms (
    id      BIGINT       NOT NULL,
    kind    VARCHAR(20)  NOT NULL,
    value   VARCHAR(100) NOT NULL,
    CONSTRAINT pk_record_terms PRIMARY KEY (id, kind, value),
    CONSTRAINT fk_record_terms_record FOREIGN KEY (id)
        REFERENCES ContentRecords (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_record_terms_kind_value ON RecordTerms (kind, value);

CREATE TABLE IF NOT EXISTS DigestRuns (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_name     VARCHAR(100) NOT NULL,
    period_start     TIMESTAMP    NOT NULL,
    period_end       TIMESTAMP    NOT NULL,
    summary_text     TEXT         NOT NULL,
    content_ids      TEXT         NULL,            -- JSON array of ContentRecords.id
    prior_digest_ids TEXT         NULL,            -- JSON array of DigestRuns.id used as context
    record_count     INT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'America/Chicago')
);

CREATE INDEX IF NOT EXISTS ix_digest_profile_end ON DigestRuns (profile_name, period_end DESC);

-- ActionRuns: deduplication log for action-dispatch (Todoist, etc.).
-- One row per (profile_name, record_id) prevents re-creating a task on re-runs.
CREATE TABLE IF NOT EXISTS ActionRuns (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_name   VARCHAR(100)  NOT NULL,
    record_id      BIGINT        NOT NULL,
    target         VARCHAR(40)   NOT NULL,   -- 'todoist'
    external_id    VARCHAR(100)  NULL,       -- provider task id
    status         VARCHAR(20)   NOT NULL,   -- created | failed
    error          VARCHAR(1000) NULL,
    action_content TEXT          NULL,       -- LLM-generated action JSON (aggregate-mode prior context)
    created_at     TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'America/Chicago'),
    CONSTRAINT uq_action_run UNIQUE (profile_name, record_id),
    CONSTRAINT fk_action_run_record FOREIGN KEY (record_id)
        REFERENCES ContentRecords (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_action_run_profile ON ActionRuns (profile_name, created_at DESC);

-- SourceDocuments: full original source text, retained untruncated. 1:1 with
-- ContentRecords (shared primary key). Kept in a separate table so the large raw
-- blobs (Postgres TOAST-compresses them out-of-line) never widen the hot
-- ContentRecords row or get pulled by an incidental SELECT *.
CREATE TABLE IF NOT EXISTS SourceDocuments (
    id          BIGINT    NOT NULL PRIMARY KEY,   -- == ContentRecords.id
    raw_html    TEXT      NULL,                    -- untruncated text/html part(s)
    raw_text    TEXT      NULL,                    -- untruncated text/plain part(s)
    captured_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'America/Chicago'),
    CONSTRAINT fk_source_doc_record FOREIGN KEY (id)
        REFERENCES ContentRecords (id) ON DELETE CASCADE
);
