"""One-time ETL: copy all ClearFeed data from SQL Server Express to PostgreSQL.

Reads from the legacy SQL Server instance (via Secrets/ClearFeed_Conn_Str.py,
Windows auth) and writes to the local Postgres database configured in src/config.py.

- Copies ContentRecords -> RecordTerms -> DigestRuns -> ActionRuns in FK order,
  preserving primary-key IDs (the Postgres identity columns are GENERATED BY
  DEFAULT, so explicit IDs are allowed).
- Resets each identity sequence past MAX(id) afterward.
- SourceDocuments is NOT backfilled: the full original source was never stored
  under SQL Server, so historical rows have no raw source. Only new ingests
  populate it going forward.
- Idempotent: TRUNCATEs the four target tables (RESTART IDENTITY CASCADE) before
  loading, so it can be re-run safely.

Usage (after schema_postgres.sql has been applied):
    python scripts/migrate_sqlserver_to_postgres.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # security_config
sys.path.insert(0, r"C:\Users\James Kupfer\Secrets")

import pyodbc  # noqa: E402
import psycopg  # noqa: E402

import config  # noqa: E402
import security_config  # noqa: E402
from ClearFeed_Conn_Str import CLEARFEED_CONNECTION_STRING  # noqa: E402

# (table, columns) in FK-safe load order. Column order is explicit so source
# SELECT and destination INSERT line up exactly.
TABLES: list[tuple[str, list[str]]] = [
    (
        "ContentRecords",
        [
            "id", "source_type", "source_ref", "received_at", "sender", "subject",
            "body_text", "linked_article_url", "image_local_paths", "image_descriptions",
            "summary", "executive_summary", "summary_confidence", "summary_rationale",
            "classification_confidence", "classification_rationale", "classify_model",
            "classify_tokens", "escalated", "enrichment_status", "enrich_attempt_count",
            "processed_at", "ingested_at",
        ],
    ),
    ("RecordTerms", ["id", "kind", "value"]),
    (
        "DigestRuns",
        [
            "id", "profile_name", "period_start", "period_end", "summary_text",
            "content_ids", "prior_digest_ids", "record_count", "created_at",
        ],
    ),
    (
        "ActionRuns",
        [
            "id", "profile_name", "record_id", "target", "external_id", "status",
            "error", "action_content", "created_at",
        ],
    ),
]

# Columns needing Python-side coercion for Postgres (SQL Server BIT -> BOOLEAN).
BOOL_COLUMNS = {"escalated"}

IDENTITY_TABLES = ["ContentRecords", "DigestRuns", "ActionRuns"]


def _coerce_row(columns: list[str], row: tuple) -> tuple:
    out = []
    for col, val in zip(columns, row):
        if col in BOOL_COLUMNS and val is not None:
            out.append(bool(val))
        else:
            out.append(val)
    return tuple(out)


def main() -> None:
    src = pyodbc.connect(CLEARFEED_CONNECTION_STRING, autocommit=True)
    dst = psycopg.connect(
        host=config.DB_HOST,
        port=config.DB_PORT,
        dbname=config.DB_NAME,
        user=config.DB_USER,
        password=security_config.DB_PASSWORD,
        connect_timeout=config.DB_TIMEOUT_SECONDS,
        autocommit=False,
    )
    try:
        scur = src.cursor()
        dcur = dst.cursor()

        # Clean slate on the destination (children first via CASCADE anyway).
        for table, _ in reversed(TABLES):
            dcur.execute(f"TRUNCATE {table} RESTART IDENTITY CASCADE")
        print("Truncated destination tables.")

        summary: list[tuple[str, int, int]] = []
        for table, columns in TABLES:
            col_list = ", ".join(columns)
            scur.execute(f"SELECT {col_list} FROM {table}")
            rows = [_coerce_row(columns, tuple(r)) for r in scur.fetchall()]

            if rows:
                placeholders = ", ".join(["%s"] * len(columns))
                dcur.executemany(
                    f"INSERT INTO {table} ({col_list}) VALUES ({placeholders})",
                    rows,
                )

            dcur.execute(f"SELECT COUNT(*) FROM {table}")
            dst_count = dcur.fetchone()[0]
            summary.append((table, len(rows), dst_count))
            print(f"  {table}: read {len(rows)} -> loaded {dst_count}")

        # Reset identity sequences so future inserts continue past the max id.
        for table in IDENTITY_TABLES:
            dcur.execute(
                "SELECT setval(pg_get_serial_sequence(%s, 'id'), "
                "COALESCE((SELECT MAX(id) FROM " + table + "), 1), "
                "(SELECT COUNT(*) FROM " + table + ") > 0)",
                (table.lower(),),
            )
        print("Reset identity sequences.")

        dst.commit()

        print("\nMigration complete. Row counts (source read -> destination):")
        ok = True
        for table, read, loaded in summary:
            match = "OK" if read == loaded else "MISMATCH"
            if read != loaded:
                ok = False
            print(f"  {table:16} {read:>7} -> {loaded:<7} [{match}]")
        print(
            "\nNOTE: SourceDocuments is intentionally empty — historical raw source "
            "was never stored under SQL Server. New ingests populate it going forward."
        )
        if not ok:
            print("\nWARNING: row-count mismatch detected; investigate before cutover.")
            sys.exit(1)
    except Exception:
        dst.rollback()
        raise
    finally:
        src.close()
        dst.close()


if __name__ == "__main__":
    main()
